// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1tQyoXSGYiWZiNx3HRXTGGPU5JWPfb5k',
    appId: '1:144423693203:android:0dd8a6b0b7281aa11c5666',
    messagingSenderId: '144423693203',
    projectId: 'chillchatv2',
    databaseURL: 'https://chillchatv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chillchatv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxy8jN2WhWU_RPZ_bQ81Ukw0_XUUPXSuI',
    appId: '1:144423693203:ios:081c1409883f6e7c1c5666',
    messagingSenderId: '144423693203',
    projectId: 'chillchatv2',
    databaseURL: 'https://chillchatv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chillchatv2.appspot.com',
    androidClientId: '144423693203-vqeurn0hs7arr5p35jnc9jmsh8a84mjo.apps.googleusercontent.com',
    iosClientId: '144423693203-p7a8q356iub39e52agmc411d6sp2tkcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chillChatV2',
  );
}
